### ISSUE TITLE
Python logo not displaying correctly?

### ISSUE THREAD

**Issue by Xalaxis** [maxerbox/vscode-discord#5]
When editing a Python file the logo seems to be set to the default rather than the expected 'double snakes'.

See [here](https://streamable.com/x0y3z) for a video of me switching between different file types to demonstrate.

**Comment by maxerbox** [comment]
I didn't added the python extension, I'm gonna add it in the next release. Since Rich Presence images need to be added manually, I've only made it compatible with a bunch of languages.

**Comment by valeth** [comment]
I have the same exact issue with most languages.
Only saw Python, JSON and JS icons so far.

Tried it with Ruby, Rust and SCSS, but they are just showing the default icon.

Using the latest canary version of Discord  VSC version 1.18.1 on Arch Linux.

**Comment by maxerbox** [comment]
Well, I have only added some assets for a few of languages (see icon map),
if you want, you can submit a list of languages you want to be added or
create a new discord app with rich presence enabled, add the language icons
and then make a pull request with the client IS in default option.

Le 24 Nov. 2017 23:15, "Patrick Auernig" <notifications@github.com> a
écrit :

I have the same exact issue with most languages.
Only saw Python, JSON and JS icons so far.

Using the latest canary version of Discord VSC version 1.18.1 on Arch Linux.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/maxerbox/vscode-discord/issues/5#issuecomment-346901507>,
or mute the thread

**Comment by Xalaxis** [comment]
Python now has a working icon in the latest version.  (Also the disposable client works really well, even without adding VSCode as a game)
